service: aws-nodejs # NOTE: update this with your service name

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:scan
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/weather

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get
    environment:
      fetch_weather_api: https://xzz4vte556.execute-api.us-west-2.amazonaws.com/dev/weather
      search_weather_api: https://xzz4vte556.execute-api.us-west-2.amazonaws.com/dev/weather/search

  fetch-weather:
    handler: functions/fetch-weather.handler
    events:
      - http:
          path: /weather/
          method: get
    environment:
      weather_table: weather

  search-weather:
    handler: functions/search-weather.handler
    events:
      - http:
          path: /weather/search
          method: post
    environment:
      weather_table: weather

resources:
  Resources:
    libraryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: weather
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1